[global]
[[global.environment]]
name = 'PSWD'
value = '<8ge8-88888888>'

[[global.environment]]
name = 'SUB_URL'
value = '<https://newbirds-sub.hf.space/upload-ea4909ef-7ca6-4b46-bf2e-6c07896ef338>'

[[global.environment]]
name = 'UUID'
value = '<ea4909ef-7ca6-4b46-bf2e-6c07896ef338>'

[[global.environment]]
name = 'MY_OTHER_ENV_VAR'
value = '<second-value>'

[[global.environment]]
name = 'MY_OTHER_ENV_VAR'
value = '<second-value>'

[[global.environment]]
name = 'MY_OTHER_ENV_VAR'
value = '<second-value>'

# ... omitted for brevity  nhost.io
